- .github/workflows/conda-tests.yml
- .github/workflows/coverage.yml
- .github/workflows/pypi-tests.yml
- README.md
- setup.cfg
- src/dask_awkward/core.py
- src/dask_awkward/tests/test_core.py
- src/dask_awkward/tests/test_getitem.py
- **getitem**: Working on dedicated paths for single key vs tuple key inputs to `getitem` (see [discussion below](https://github.com/ContinuumIO/dask-awkward/pull/28#discussion_r789717041)).
- Followup PR(s) to continue this
- **packaging**: improving setup.cfg
- **misc**: typetracer detection and utilities for grabbing typetracers from heterogenous mixed sequences of objects
> Continued development

- pyproject.toml
- src/dask_awkward/core.py
- src/dask_awkward/io.py
- src/dask_awkward/reducers.py
- src/dask_awkward/structure.py
- src/dask_awkward/tests/conftest.py
- src/dask_awkward/tests/test_core.py
- src/dask_awkward/tests/test_getitem.py
- src/dask_awkward/tests/test_reducers.py
- src/dask_awkward/tests/test_structure.py
- src/dask_awkward/tests/test_ufunc.py
- src/dask_awkward/testutils.py
- src/dask_awkward/utils.py
- more work on structure & reducer functions
- improvements to partitionwise with aggregation to scalar
-  improving test infra
- proper organization (use `conftest.py` for shared fixtures)
- improvements to JSON I/O
- leverage `fsspec`
- use wrapper callables
- infer compression
> struture and reductions; extending partitionwise with aggregation to scalar; tests; JSON I/O

- src/dask_awkward/__init__.py
- src/dask_awkward/awkward.yaml
- src/dask_awkward/config.py
- src/dask_awkward/core.py
- src/dask_awkward/tests/test_core.py
- src/dask_awkward/tests/test_describe.py
- Adding an `awkward` entry to `dask.config`
- The only option so far is `compute-unknown-meta` which by default is set to `True`. If the option is `False`, when a new collection is created with unknown meta we will leave it as `None`. (The default behavior is to use the first partition to compute metadata (typetracer array) eagerly.
- rename the `meta` property to `_meta` (consistent with core Dask collections)
- also "privatize" the typetracer property as `_typetracer`
- Use Dask's `dask.config.set` context manager for setting `awkward.compute-unknown-meta` to `False` instead of the `ignore_meta` kwarg described in #37
> use dask.config; rename meta property to _meta, also privatize typetracer

- src/dask_awkward/__init__.py
- src/dask_awkward/core.py
- src/dask_awkward/reducers.py
- src/dask_awkward/structure.py
- src/dask_awkward/tests/test_core.py
`map_partitions` has been given a new argument: `output_divisions` for defining the behavior of the divisions of the output.
- `None` (the default) will cause divisions to be wiped clean. `npartitions` will remain the same but we will "forget" the divisions, as we have no way of knowing if the divisions changed.
- `1` will conserve the existing divisions. Something like `x["attr"]` or `dak.max(x, axis=1)` conserves divisions.
- Anything greater than 1: Multiplies the existing divisions by this factor.
> New `output_divisions` argument for `map_partitions`

- src/dask_awkward/__init__.py
- src/dask_awkward/core.py
- src/dask_awkward/tests/test_behavior.py
- src/dask_awkward/tests/test_structure.py
- src/dask_awkward/tests/test_utils.py
- src/dask_awkward/utils.py
> Awkward behaviors support

- pyproject.toml
- src/dask_awkward/__init__.py
- src/dask_awkward/core.py
- src/dask_awkward/structure.py
- src/dask_awkward/testutils.py
- src/dask_awkward/typing.py
- src/dask_awkward/utils.py
- tests/test_behavior.py
- tests/test_core.py
- tests/test_distributed.py
- tests/test_getitem.py
- tests/test_io.py
- tests/test_structure.py
- Little helpers in `testutils`
- Adding `axis=1` top level `ak.*` namespace functions for:
- `cartesian`
- `firsts`
- Other `ak.` namespace functions:
- `with_name`
- `ones_like`
- `zeros_like`
- Scalar repr fix
- some typing improvements
- docstring improvements
> General development

- .pre-commit-config.yaml
- src/dask_awkward/core.py
- src/dask_awkward/io/io.py
- tests/conftest.py
- tests/test_core.py
- tests/test_io.py
- Add support for `to_dask_array` where the awkward array collection is known to be multidimensional.
- Refactor the computation of metadata in cases where it's unknown
> to_dask_array support for ndim > 1; refactor meta determination.

- docs/conf.py
- docs/intro.rst
- pyproject.toml
This tiny PR does two things:
1. Correct the demo code @douglasdavis can you check that my "fix" is correct for the `intro.rst` Dask example?
2. Adds sphinx-design and uses panels to compare awkward with dask-awkward:
> docs: use sphinx-design to compare Awkward

- src/dask_awkward/lib/core.py
- src/dask_awkward/lib/reducers.py
- src/dask_awkward/lib/structure.py
Replaces `pw_reduction_with_agg_to_scalar` (partitionwise reduction with aggregate to scalar) with `_total_reduction_to_scalar`. The former uses a low level graph for the reduction step. The later is now all high level graphs. This isn't quite as flexible as the upstream dask `apply_concat_apply` strategy, but it's a good step in that direction. This code will certainly evolve over time as needed.
> Total reduction with high level layer(s)

- src/dask_awkward/lib/io/parquet.py
- src/dask_awkward/lib/testutils.py
- tests/conftest.py
- tests/test_parquet.py
this PR fixes `from_parquet` in two areas:
1. the case where the we have an "unnamed root" in a column (e.g. `.list.item.column.list.item`)
2. the case where splitting by row groups created a task graph that was one element too small
> parquet fixes

- src/dask_awkward/lib/io/parquet.py
@martindurant does this make sense? (without this `dak.to_parquet(array, "some_dir")` crashes if `some_dir` doesn't exist)
> to_parquet: mkdirs

- .github/workflows/conda-tests.yml
- .github/workflows/coverage.yml
- .github/workflows/pypi-tests.yml
This PR adds the following YAML to the GitHub Actions CI configuration, so that multiple pushes cancel previous running jobs
```yaml
concurrency:
group: '<NAME>-${{ github.head_ref || github.run_id }}'
cancel-in-progress: true
```
> ci: add concurrency groups

- pyproject.toml
- src/dask_awkward/lib/inspect.py
- src/dask_awkward/lib/io/parquet.py
- src/dask_awkward/lib/optimize.py
- src/dask_awkward/lib/testutils.py
- src/dask_awkward/lib/utils.py
- tests/test_inspect.py
- tests/test_optimize.py
- tests/test_structure.py
Adds a new `dask_awkward.lib.inspect` module with the `necessary_columns` function for inspecting which IO columns are necessary in a given graph.
> Necessary columns logic usable via utility functions

- pyproject.toml
- src/dask_awkward/lib/core.py
scikit-hep/awkward#1922 changes the `ak.contents.Content`/`ak.record.Record` API to use a new high-level `backend` object instead of `nplike`. This is just to better encapsulate the difference between an array compatibility library, and a "backend". 
This PR adjusts the dask-awkward usage of the old `.nplike` attribute in favour of the new `.backend` object, which has a `.nplike` and `.index_nplike` member.
Note that this code has *not* been released yet, so I've bumped the `pyproject.toml` to look for a new version of awkward.
> fix: use new `backend` attribute instead of `nplike`

- pyproject.toml
- src/dask_awkward/lib/core.py
- tests/test_structure.py
- ipython methods needed to conserve the mechanism we use to check for
behaviors (methods on the metadata)
- remove string fill value for fill_none tests; raises warning and
computes first partition due to typetracer operation error
> add some _ipython* methods and remove some warnings

- src/dask_awkward/lib/structure.py
- tests/test_structure.py
Fixes https://github.com/dask-contrib/dask-awkward/issues/121
> Add dak.unzip

- src/dask_awkward/lib/structure.py
- tests/test_structure.py
> Add dak.where

- src/dask_awkward/lib/structure.py
- tests/test_structure.py
This is necessary since field assignment into `dak.Array` RecordArrays cannot be done with square brackets.
> Add dak.with_field

- src/dask_awkward/lib/reducers.py
Removed in [awkward v2.0.3](https://github.com/scikit-hep/awkward/releases/tag/v2.0.3)
> Remove `flatten_records` kwarg for reducers

- pyproject.toml
- src/dask_awkward/sizeof.py
- tests/test_sizeof.py
Use Dask's `dask.sizeof` entry-point to [register sizeof usage](https://docs.dask.org/en/stable/how-to/extend-sizeof.html) for `awkward.Array` object
> Register with dask.sizeof

- src/dask_awkward/lib/structure.py
Workaround for https://github.com/scikit-hep/awkward/issues/2092.
This just precalculates the meta for axis > 0 cases using the typetracer's `form.length_zero_array()`
> Take ak.num meta from form.length_zero_array()

- src/dask_awkward/config.py
This new implementation makes sure to conserve all entries in the existing `allowed-imports` configuration option for the distributed scheduler
> `distributed.scheduler.allowed-imports` config update

- src/dask_awkward/lib/structure.py
- tests/conftest.py
- tests/test_core.py
- tests/test_structure.py
Fixes #124
Fixes #128
add:
- argcartesian
- argcombinations
- isclose
- singletons
- argsort (for axis > 0, from #130)
- sort (for axis > 0)
- appropriate error for copy
- full_like (needs issue on awkward opened for meta calculation)
- unflatten (currently simplistic implementation, needs work to be general since it requires repartitioning, but very important/necessary)
- to_packed
- ravel (with warnings about recordarrays)
- run_lengths (with warning about axis=0)
- from_regular
- to_regular
- broadcast_arrays (#128)
remove:
- concatenate impl in `structure.py`
> Add more ak verbs

- pyproject.toml
- src/dask_awkward/awkward.yaml
- src/dask_awkward/config.py
- src/dask_awkward/lib/core.py
- tests/test_getitem.py
This PR changes the way metadata is handled at graph creation time.
1. We've added a configuration parameter `awkward.raise-failed-meta` that, when `True` (default is `False`), will raise an exception during graph creation time if the process of determining a new metadata (typetracer array) fails. For example, in `map_partitions(fn, array)` we always call `fn(array._meta)` to determine the "new" meta on the graph. By default, if this fails we will compute the first partition and issue a warning. The new configuration option will hard fail instead of warning.
2. We've added an additional code path for determining the new meta via a call on a length zero array _instead_ of a high level typetracer array. (the default behavior is to always try on a high level typetracer array). If the new …
> Adjust `_meta` determination during graph construction (new config parameter, length zero array fallback)

- src/dask_awkward/lib/core.py
Use deps instead of args since expressions like `1-x` doesn't have a dask collection for `arg[0]`.
> Only use dask collections to determine divisions/partitions

- src/dask_awkward/lib/optimize.py
fixes #172
the optimization always touches all fields in an array if it's the last array in a task graph. we were making an incorrect assumption about the output layer always being the last in the list of layer dictionary values. this PR makes use of the HLG topologically sorted layers method
> Fix layer order assumption in optimization

- src/dask_awkward/lib/io/io.py
- src/dask_awkward/lib/io/parquet.py
@lgray is this what you had in mind?
```python
to_parquet(a, "/output/path", prefix="abc")
```
will write files of the form (50 partitions):
```
/output/path/abc-part00.parquet
...
/output/path/abc-part49.parquet
```
while
```python
to_parquet(a, "/output/path")
```
remains
```
/output/path/part00.parquet
...
/output/path/part49.parquet
```
(took the opportunity to add a bit of typing to this PR as well)
> Add ability to have file prefix in to_parquet

- src/dask_awkward/lib/core.py
- tests/test_getitem.py
Resolves #188.
I don't know if there's a preferred way to handle this, but this was the solution that I found. I believe the `contents` nesting can be arbitrarily deep, so I think there has to be a loop over them, unless there's an `awkward` shortcut that I'm not aware of.
> Recurse through nested contents for arrays used in `getitem`

- src/dask_awkward/lib/core.py
- tests/test_structure.py
Restore expected behavior from awkward arrays, namely being able to set record-array fields via `__setitem__`.
Doesn't work yet - help or tips appreciated :-)
> feat: `__setitem__` by way of using dak.with_field

- docs/dev-contributing.rst
This may only be an issue when using macs.
Without the "" I get zsh: no matches found: .[complete]
> DOC: quotes around .[complete]

- src/dask_awkward/lib/core.py
- tests/test_getitem.py
Follow up to #217; there are some cases that are not map-partitionable; for now raise on those.
> fix: raise for non-map-partitionable `getitem` calls with ellipsis

- pyproject.toml
- src/dask_awkward/lib/structure.py
This can be relaxed now but is still a consequence of #223.
> Modify workaround for touching `what` in dak.with_name

- src/dask_awkward/lib/core.py
- tests/test_behavior.py
remove odd constructions in user code like:
```python3
events.some_behavior_method(*args, _dask_array_=events)
```
> Substitute in self for _dask_array_ when it is not specified

- src/dask_awkward/lib/structure.py
- tests/test_structure.py
Present implementation of singletons was failing column optimization when passed RecordArrays that were then accessed later.
> fix: make ak.singletons workaround operate correctly in all cases

- src/dask_awkward/lib/structure.py
> fix: remove zero_length_array meta calculation in full_like

- src/dask_awkward/lib/core.py
- src/dask_awkward/lib/structure.py
- tests/test_structure.py
Partially fixes #226 for `where` and `with_field`
Allows users to pass in non-dak arguments for certain arugments of where and with_field.
@yimuchen
> feat: Allow `dak.where`, `dak.with_field` and `__setitem__` to take some non-array arguments

- src/dask_awkward/layers/layers.py
- src/dask_awkward/lib/optimize.py
- tests/test_core.py
Fixes #233
Posting a PR with @martindurant's patch to lodge here results of conversation / hacking in slack.
With some of the suggested changes in https://github.com/dask-contrib/dask-histogram/pull/74, it makes the complete analysis chain optimizable looking at only one partition per input dataset.
> fix: only do column optimization on one partition of input dataset

- src/dask_awkward/lib/structure.py
Addressing changes in https://github.com/scikit-hep/awkward/pull/2429
Typetracer touching confirmed correct in complex cases involving numerical arguments to where/with_field.
> Remove typetracer work arounds in where and with_field

- src/dask_awkward/lib/core.py
- src/dask_awkward/lib/structure.py
This PR removes the last `length_zero_array()` usages in the dask-awkward operations, and also accounts for an upcoming deprecation of `highlevel=True` in `length_zero_array` (scikit-hep/awkward#2435)
> fix: drop workarounds for typetracer, use `highlevel=False`

- pyproject.toml
- src/dask_awkward/layers/layers.py
> **Warning**
> This will require a pin on a future release of awkward (2.2.1). 
We're gradually exporting any clearly-needed features from Awkward into a public (L2) module, in this instance `ak.typetracer`. This PR makes use of these symbols.
> fix: import `typetracer_with_report` from L2 module

- src/dask_awkward/lib/core.py
Update needs this fix for its tests to pass (even [on main](https://github.com/scikit-hep/uproot5/actions/runs/5156709074)).
We'll need a dask-awkward release before we can do another release of Uproot.
> fix: update to scikit-hep/awkward#2454.

- src/dask_awkward/layers/layers.py
Dask needs a task to be a `tuple`, if it's a `list` then dask just assumes the `list` is a literal to be returned (basically an already computed thing) instead of a lispy s-expression to be executed
> fix: (in `AwkwardMaterializedLayer.mock`) tasks should be tuples

- src/dask_awkward/lib/core.py
creating a whole list is not necessary
> fix: optimize next division calculation in zeroth slicing

- src/dask_awkward/lib/unproject_layout.py
We want to allow `unproject_layout` to be called in cases where the "original form" may be ``None`` (i.e. no column optimization occurred or it maybe failed). In these cases just return the layout.
> fix: in `unproject_layout` protect against `None` form; add docstring

- src/dask_awkward/layers/__init__.py
- src/dask_awkward/layers/layers.py
- src/dask_awkward/lib/core.py
Discovered the need for this in for typetracer only graphs (for column opt) to work after #267.
> feat: add mock-able `AwkwardTreeReductionLayer` class

- .github/workflows/awkward-main.yml
- .github/workflows/conda-tests.yml
- .github/workflows/coverage.yml
- .github/workflows/pypi-tests.yml
- pyproject.toml
- src/dask_awkward/layers/layers.py
- src/dask_awkward/lib/core.py
- src/dask_awkward/lib/io/io.py
- src/dask_awkward/lib/io/parquet.py
- src/dask_awkward/lib/operations.py
- src/dask_awkward/lib/testutils.py
- src/dask_awkward/lib/unproject_layout.py
- tests/conftest.py
- tests/test_behavior.py
- tests/test_core.py
- tests/test_distributed.py
- tests/test_operations.py
This PR is an experiment in hardening our existing tests.
Many of our tests are performed by using the `daa` and `caa` fixtures.
- `daa` is a dask-awkward `Array` that is created via `dak.from_json`. 
- `caa` is a concrete awkward `Array` created from `ak.from_json` followed by `ak.concatenate`. 
the structure of the array is:
```
n * {
points: var * {
x: int64,
y: int64
}
}
```
(a record array with a single entry (`points`) which each contain a variable number of `(x, y)` pairs)
This makes it easy to write a test like:
```python
def test_sum_axis1(daa, caa):
assert_eq(
dak.sum(daa.points.x, axis=1),
dak.sum(caa.points.x, axis=1),
)
```
Currently dask-awkward JSON reads do not support the `project_columns` interface (though it is something on our todo list).
So `daa.points.x` will not be …
> refactor: harden tests by adjusting current array-providing fixtures

- src/dask_awkward/lib/core.py
- src/dask_awkward/lib/reducers.py
- tests/test_reducers.py
- ~[x] Support positional reducers~
> feat: add comprehensive `axis=0` and `axis=None` reduction

- src/dask_awkward/lib/core.py
- tests/test_core.py
This will allow more expressive signatures as inputs to map_partitions.
Resulting code is pleasantly clean.
> feat(map_partitions): allow for dask collections to be passed as kwargs or as part of higher level structures

- tests/test_structure.py
will remove this when #307 is figured out; these failures are unrelated to other ongoing work where we want passing CI
> chore: temporarily xfail sort and argsort tests

- docs/api-inspect.rst
- src/dask_awkward/lib/__init__.py
- src/dask_awkward/lib/core.py
- src/dask_awkward/lib/operations.py
- src/dask_awkward/lib/structure.py
- src/dask_awkward/utils.py
- tests/test_core.py
TL;DR
- existing `dak.compatible_partitions` gets a new argument (`how_strict`) which provides some user-definable passing criteria. (existing uses of the function are unchanged, just a new argument where the default value lines up with current behavior).
- new function `dak.partition_compatibility` along with new sum type `PartitionCompatibility` can be used for more flexibility.
---
This PR introduces a `partition_compatibility` function that returns a sum type (the new `PartitionCompatibility` enum) that can be `YES`, `NO`, or `MAYBE`. This will allow downstream code to use `MAYBE` as desired. In dask-awkward we will simply use `NO` to raise exceptions.
Any place that was original checking
```python
if not dak.compatible_partitions(a, b):
raise IncompatiblePartitions(...)
```
can now …
> feat: do partition compat. checks with `PartitionCompatibility` sum type

- pyproject.toml
- src/dask_awkward/lib/optimize.py
- tests/test_optimize.py
Fix #299 
@lgray your reproducer in #299 runs for me with this PR!
I'm surprised at how small of a code change this is w.r.t. how gnarly of a problem it seemed when I first started digging into upstream dask code 😛
> fix: ensure that we can `dask.compute` multiple collections simultaneously

- src/dask_awkward/lib/structure.py
- src/dask_awkward/lib/unproject_layout.py
- tests/test_io.py
This reverts our form hydration feature originally added in https://github.com/dask-contrib/dask-awkward/pull/184. It appears to have triggered #313 and #314. We need more testing of the feature before it's ready.
This PR is an alternative to #317. In that PR we not only revert unproject_layout's action, but we also introduce more touching in the column optimization to make up for what unproject_layout was trying to accomplish. Unfortunately using `shape_touched` from the typetracer report causing over-touching of data.
cc @lgray
> fix: make `unproject_layout` do nothing (just return original layout)

- src/dask_awkward/lib/core.py
- tests/test_core.py
> fix: make `dak.Array` copy-able

- src/dask_awkward/lib/core.py
- tests/test_core.py
based on convsersation in IRIS-HEP slack; it's possible to call a dask-awkward version of an awkward function but pass in concrete Arrays. Before this PR we hit a confusing `IndexError` when no 
collections were found. This will raise a less confusing error
> fix: better error message when no collections passed to `map_partitions`.

- src/dask_awkward/lib/core.py
- src/dask_awkward/lib/structure.py
- tests/test_core.py
Make a new attribute `defined_divisions` on `dak.Array`; if it's used when `Array.known_divisions` is `False` we'll raise an exception. It _always_ returns a tuple if ints (the case where divisions are known, when divisions are unknown we have a tuple of `None`s)
This helps in two ways:
1. we have a way to write code in situations where we know divisions are known (and are necessary in that piece of code) and raise an exception when they are not (e.g. slicing and repartitioning)
2. static typing is a mess in sitations where we know divisions because we're having to deal with divisions being `tuple[int | None, ...]`.
> feat: add new attribute for when divisions are known

- src/dask_awkward/lib/io/io.py
- tests/test_io.py
This change fixes the ValueError that is raised if one tries to use from_awkward on an empty awkward array. For example by executing  `dak.from_awkward(ak.Array([]), 1)`.
> Fix error when using from_awkward on an empty array

- src/dask_awkward/__init__.py
Quite a while ago we moved all parts of `dask_awkward` that import upstream `awkward` inside of a `lib` submodule and made the top level `__init__.py` use `__getattr__` to find classes and functions in `lib` on-demand. The purpose of this was to avoid importing `awkward` unnecessarily (i.e. on a remote dask scheduler). As of `dask==2023.4.0` and `distributed==2023.4.0` the scheduler is now required to have the same installed packages as the client and workers [1], so this workaround is now pointless. It will make life easier (and make finding function definitions/references in IDEs easter) if we use simple top level namespace imports.
[1] https://distributed.dask.org/en/stable/changelog.html#v2023-4-0
> chore: add main API functions & classes to top level `__init__.py`

- src/dask_awkward/lib/structure.py
- tests/test_structure.py
> fix: Lazy `dak.num(..., axis=0)` (or negative axis that is equivalent to `axis=0`)

- docs/ht-configuration.rst
- docs/me-optimization.rst
- src/dask_awkward/awkward.yaml
- src/dask_awkward/lib/optimize.py
@martindurant - would like your take here. I've been tinkering with tests for the JSON column optimization and I'd like to able to do some graph surgery in the tests to get at results from the input layer (that is, get directly at the result of the call of `ak.from_parquet` or `ak.from_json`), but if the layer chaining occurs it's a bit more difficult to do that.
With this PR no functionality changes, just more config flexibility
> feat: configuration can handle list of optimizations to run

- .github/workflows/uproot-main.yml
this way we get a dask-awkward version generated that satisfies uproot
> ci: use fetch-depth 0 to get tags for correct versioning

- src/dask_awkward/lib/testutils.py
- tests/test_parquet.py
following our solving of #346 we can xfail failing tests based on version combinations
> fix: xfail some parquet tests due to `item -> element` change in pyarrow 13

- src/dask_awkward/lib/optimize.py
- src/dask_awkward/lib/structure.py
This is not yet released in `awkward`.
> refactor: use `ak.typetracer.touch_data`

- src/dask_awkward/lib/io/io.py
- tests/test_io.py
Pulling this out of the JSON PR (#94) because we'll also use it for `from_text` (prototype here: https://github.com/douglasdavis/dask-awkward/pull/7)
> feat: add `bytes_with_sample` for creating bytes reading instructions

- pyproject.toml
- src/dask_awkward/pickle.py
- tests/test_pickle.py
Fixes #344 by overriding the default Awkward `__reduce__` implementations.
Requires https://github.com/scikit-hep/awkward/pull/2682
> feat: add custom pickle implementation

- src/dask_awkward/__init__.py
- src/dask_awkward/layers/layers.py
- src/dask_awkward/lib/__init__.py
- src/dask_awkward/lib/core.py
- src/dask_awkward/lib/io/io.py
- src/dask_awkward/lib/io/parquet.py
- tests/test_io.py
Depends upon https://github.com/scikit-hep/awkward/pull/2671
> refactor: use `ak.typetracer.XX` high-level functions

- docs/api/io.rst
- docs/conf.py
- docs/how-to/io.rst
- docs/more/optimization.rst
- pyproject.toml
- src/dask_awkward/lib/core.py
- src/dask_awkward/lib/io/text.py
> docs: add documentation for `from_text`

- src/dask_awkward/lib/testutils.py
- tests/test_parquet.py
> fix: remove unnecessary pyarrow import in `testutils`

- src/dask_awkward/__init__.py
- src/dask_awkward/lib/__init__.py
- src/dask_awkward/lib/core.py
- src/dask_awkward/lib/str.py
- tests/test_str.py
Following https://github.com/scikit-hep/awkward/pull/2616 we can add `dask_awkward.str`
> feat: support `ak.str` as `dak.str`

- .github/workflows/awkward-main.yml
- .github/workflows/conda-tests.yml
- .github/workflows/coverage.yml
- .github/workflows/pypi-tests.yml
When we install `dask-awkward` we get the version from git; so we need to fetch all tags in CI to make sure uproot knows we have a compatible dask-awkward version installed.
> ci: use `fetch-depth: 0` because uproot version checks dask-awkward

- src/dask_awkward/lib/optimize.py
- tests/test_optimize.py
> fix: simultaneous computes when one is encapsulated by the other doesn't over optimize

- .pre-commit-config.yaml
- docs/dev/contributing.rst
- pyproject.toml
- src/dask_awkward/layers/layers.py
- src/dask_awkward/lib/core.py
- src/dask_awkward/lib/inspect.py
- src/dask_awkward/lib/io/columnar.py
- src/dask_awkward/lib/io/io.py
- src/dask_awkward/lib/io/json.py
- src/dask_awkward/lib/io/parquet.py
- src/dask_awkward/lib/optimize.py
- src/dask_awkward/lib/utils.py
- tests/conftest.py
- tests/test_core.py
- tests/test_io_json.py
we've always had type hints throughout dask-awkward but it's never been formalized, this PR aims to clarify typing in the project.
> fix: harden typing in the code base; add pre-commit check; improve docs

- .github/workflows/coverage.yml
- .github/workflows/pypi-tests.yml
- pyproject.toml
I noticed that we were failing in CI due to Arrow being installed from sdist on Python 3.12.
In future, perhaps these large binary dependencies should not be installed from source as a rule. That might be a forward-looking thing to do, we also need to just ensure we don't install PyArrow here, because it's not yet available on 3.12.
This PR changes our CI to avoid pulling in `pyarrow` via `dask`, and also ensures that our own `pyproject.toml` just skips `pyarrow` and `aiohttp` if we are on 3.12
> fix: declare pyarrow optional for 3.12

- .pre-commit-config.yaml
- src/dask_awkward/lib/core.py
- tests/test_core.py
This adds support for binary and unary operations with the `Scalar` collection, fixing #396
It also changes the existing `__getattr__` implementation on the `Scalar` object. It was there to support _any_ kind of Python Scalar object by just converting to delayed, but having this breaks IPython. We should raise an error that instructs the user to convert to delayed.
> feat!: add `Scalar` binary and unary ops; adjust `Scalar.__getattr__`

- src/dask_awkward/layers/layers.py
- src/dask_awkward/lib/core.py
- tests/test_core.py
Followup to https://github.com/dask-contrib/dask-awkward/pull/397
> feat: add support for `Array` collection broadcasting with `Scalar` collection

- src/dask_awkward/lib/core.py
> fix: use duck-typing check in place of `isinstance(..., np.ndarray)`

- pyproject.toml
- src/dask_awkward/layers/layers.py
- src/dask_awkward/lib/io/columnar.py
- src/dask_awkward/lib/io/io.py
- src/dask_awkward/lib/testutils.py
- tests/test_io.py
Discussed on Slack, this is a way to give `from_map` callers the ability to provide a list of "allowed" exceptions that should just return an empty array. It requires the `io_func` to have a `form` attribute such that a correctly formed empty array can be instantiated. cc @lgray 
To use this new feature there are two requirements:
1. Write a `mock_empty` method (that takes a single argument that should be passed to `ak.to_backend`) in the class function passed to `from_map`. (The `ColumnarProjectionMixin` class in the `lib.io.columnar` module provides an example implementation).
2. pass values to the `empty_on_raise` and `empty_backend` arguments of `from_map`. `tests/test_io.py` has example `from_map` calls that includes values for these arguments
> feat: support returning empty arrays in `from_map` IO function calls based on user declared exceptions

- src/dask_awkward/layers/layers.py
- src/dask_awkward/lib/io/columnar.py
- src/dask_awkward/lib/io/io.py
- tests/test_io.py
Followup to regression introduced in #400
> fix: don't require `mock` and `mock_empty` together; use behaviors in empty array creation

- src/dask_awkward/lib/structure.py
This is a small PR to enforce some more type hints
> refactor: enforce more type hints

- src/dask_awkward/lib/structure.py
- tests/test_structure.py
My recent change to `dak.copy` made it an identity. Whilst that's useful _at the buffer level_ (dask-awkward has only pure functions at the user level) we still want to copy the metadata. This will become _more_ important with `Array.attrs`.
> fix: `dak.copy` should copy metadata

- src/dask_awkward/lib/structure.py
`np.int64` is not a proper dtype, `np.dtype("int64")` is.
> fix: bad dtype definition for `dak.num(..., axis=0)` metadata

- src/dask_awkward/lib/core.py
- tests/test_core.py
- tests/test_io.py
- tests/test_io_json.py
I've seen new users not immediately understanding that `len` calls are eager when divisions are unknown and wondering why their analysis code takes too long before finding out it was just a couple of `len` calls that shouldn't be there.
I was a victim of this myself. Therefore, I think a good idea would be to add a warning.
> feat!: raise error to eager `len` calls

- pyproject.toml
- src/dask_awkward/lib/core.py
- src/dask_awkward/lib/io/io.py
- src/dask_awkward/lib/io/json.py
- src/dask_awkward/lib/io/parquet.py
- src/dask_awkward/lib/operations.py
- src/dask_awkward/lib/reducers.py
- src/dask_awkward/lib/str.py
- src/dask_awkward/lib/structure.py
- tests/test_getitem.py
- tests/test_structure.py
This PR adds support for `awkward==2.5.0`'s latest features, including `attrs` and a public typetracer API.
> feat: update to latest `awkward==2.5.0`

- src/dask_awkward/lib/core.py
- src/dask_awkward/lib/optimize.py
- src/dask_awkward/lib/structure.py
The `opt_touch_all` argument to `map_partitions` was added to make layers manually touchable (that is, tell the optimization code to not rely on the typetracer graph for touching in that layer, just touch all awkward data at that point). This allowed us to workaround operations where automatic typetracer touching wasn't working. 
It was only used with `dak.zip`, but with the work on upstream typetracer and the optimization refactor here in dask-awkward, I think we're in a place now where we don't need it.
It's currently used in coffea, see: https://github.com/CoffeaTeam/coffea/issues/915
> feat: deprecate `opt_touch_all` from `map_partitions`.

- docs/api/behavior.rst
- docs/index.rst
- src/dask_awkward/__init__.py
- src/dask_awkward/lib/core.py
- tests/test_behavior.py
This PR is a suggestion for replacing `_dask_array_` with an extension to the descriptor protocol, namely `_dask_get`, `_dask_set`, etc.
The motivations for this are to avoid reserving a name within the function signatures, keep property descriptors looking like property descriptors, and to avoid the need to compute the function signature.
Unfortunately, if the fallback case of using `map_partitions` were implemented naively, we'd need to support a collection type that represents an `Any` type. As this isn't feasible, this PR uses a heuristic (as we already do) to determine whether the descriptor represents a method (in which case, delaying the call to map_partitions). The heuristic that I chose is to test whether the resolved attribute is `callable`.
If we are interested in this PR, then …
> feat: add new dask-behavior protocol

- src/dask_awkward/lib/structure.py
This is causing a failure over in https://github.com/CoffeaTeam/coffea/pull/925
Will need a dask-awkward 2023.11.5 :-)
> fix: dak.firsts should be able to take any axis >= 1 in common case

- src/dask_awkward/awkward.yaml
Generally a column optimization failure results from a genuine logic error in creating the dask taskgraph that users want to execute, and hiding that logic error behind continuing with a failed optimization more typically results in incorrect results as well as extremely worsened io performance for the compute task.
This PR changes the default so that we fail early, which is a better fit given the much advanced state of the typetracer interface in awkward compared to when this fall-through was written.
We should suggest that if a user is doing something that will intentionally fail the column optimization they should instead turn it off rather than attempt the optimization over and over!
> feat!: change default behavior of column optimization failure to raise

- src/dask_awkward/layers/layers.py
- src/dask_awkward/lib/io/columnar.py
- src/dask_awkward/lib/io/io.py
- src/dask_awkward/lib/io/json.py
- src/dask_awkward/lib/io/parquet.py
- src/dask_awkward/lib/io/text.py
- src/dask_awkward/lib/testutils.py
- src/dask_awkward/utils.py
- tests/conftest.py
- tests/test_core.py
- tests/test_io.py
- tests/test_parquet.py
This supersedes #415
**High level overview**: dask-awkward's `from_map` function takes a callable as the first argument (`func`). If that callable has a `return_report` property that returns ``True``, then `from_map` will return **two** collections. The first will be the `Array` collection of interest (computes to be the intended data array) and the second will be another `Array` collection that computes to some user defined thing implemented for the specific `func` that gets passed into `from_map`.
> feat: add interface for returning reports from function classes passed to `from_map`

- src/dask_awkward/pickle.py
- tests/test_pickle.py
This PR should have been done earlier (it fell off my To-Do list!). It introduces a versioned unpickling scheme (through dedicated unpickling functions) that ensures we also serialise the `attrs` and `behavior` dictionaries. As per the semantics of `attrs`, we drop any prefixed keys.
@lgray it occurs to me that inter-worker transfer would break arrays which depend upon `@foo` keys existing in the attrs dict. I can't imagine that we would want that. Maybe we need to discuss the issue further, though this PR can merge as-is.
Closes #427
> fix: pickle array attributes

- src/dask_awkward/lib/core.py
- tests/test_core.py
Broadcasting will occur equivalently at each partition because the Delayed object is *not* partitioned (as shown in the test added in this PR).
> feat: add support for `Delayed` in partitionwise layer creation.

- docs/conf.py
- pyproject.toml
The Dask specific Sphinx theme is breaking on RTD; this PR is meant as a temporary fall back to the non Dask branded version for now to make sure we have docs building successfully.
> docs: fix RTD build

- src/dask_awkward/lib/inspect.py
- src/dask_awkward/lib/optimize.py
- tests/test_io_json.py
- tests/test_optimize.py
@douglasdavis I think this fixes #426.
However, I changed the type hints and made a subtle change to appease the type checker. I'm not convinced it's correct and would appreciate your input. I'll tag you at the edit site.
In our tests we assume that we can pass in `keys=[]`. Is that supposed to be the way that `dask.optimize` is used?
> fix: pass `keys` to column optimisation

- src/dask_awkward/lib/io/json.py
- src/dask_awkward/lib/io/parquet.py
> fix: `to_{parquet,json}` retain complete path 

- src/dask_awkward/layers/layers.py
- tests/test_inspect.py
Another possible fix to #468, perhaps the simplest.
@agoose77 @martindurant @jpivarski
> fix: projected AwkwardInputLayers have __dask_tokenize__

- src/dask_awkward/lib/unproject_layout.py
- tests/test_unproject_layout.py
Fixes a bug reported by @NJManganelli in which an un-needed mask was not specialised to the appropriate `valid_when` value.
@NJManganelli can we vendor your reproducer parquet file for our tests?
> fix: build proper mask in `unproject_layout`

- src/dask_awkward/lib/core.py
This PR splits `map_parititions` into itself and an unsafe version `_map_partitions` which does not make the effort to sanitize input functions or data.
This avoids creating an ArgsKwargsPackedFunction when it is not necessary to do so in routine operations like getitem and fancy indexing.
Saves O(1)s in a complex analysis.
> perf: private map partitions

- src/dask_awkward/lib/io/io.py
Call the report output `report` and the from-uproot part `from-uproot` (or whatever input file format it happens to be) but with a different token key.
> feat: more obvious names for report products

- src/dask_awkward/lib/io/io.py
This lets us scale past ~30k input partitions without hitting a recursion error from ak.concatenate.
@nsmith- give this a try if you have time, should only need a client-side update.
> feat: use tree reduction to aggregate i/o report

- pyproject.toml
As per https://github.com/dask-contrib/dask-awkward/pull/483#issuecomment-1994730138
> build: add dask[dataframe] for test deps

- src/dask_awkward/lib/inspect.py
- src/dask_awkward/lib/optimize.py
- src/dask_awkward/lib/utils.py
- tests/test_utils.py
Will have no effect until https://github.com/scikit-hep/awkward/pull/3054 is out
@lgray , any other places we need this optimisation?
> feat: turn off ak's typetracer _new checks during optimize

- src/dask_awkward/__init__.py
- src/dask_awkward/lib/__init__.py
- src/dask_awkward/lib/describe.py
- src/dask_awkward/lib/structure.py
- tests/test_behavior.py
- tests/test_describe.py
- tests/test_inspect.py
- tests/test_structure.py
The _tests_ need type annotations! That's too much, man!
> feat: add 'dak.backend' and `dak.to_list` and verify that they overload the `ak.*` versions

- src/dask_awkward/lib/structure.py
- tests/test_optimize.py
- tests/test_structure.py
> feat: Implement dak.nan_to_num

- src/dask_awkward/__init__.py
- src/dask_awkward/lib/__init__.py
- src/dask_awkward/lib/structure.py
- tests/test_structure.py
> feat: add `dask_awkward.without_field`

- .pre-commit-config.yaml
- pyproject.toml
- src/dask_awkward/lib/core.py
- tests/test_core.py
> fix: Respect inverse in scalar binop

- docs/api/utils.rst
- docs/index.rst
- src/dask_awkward/lib/core.py
- src/dask_awkward/utils.py
- tests/test_core.py
- tests/test_io_json.py
This fixes #538 by adopting to dask.Array's behavior. 
However, I think - in the long run - we should aim for avoiding "silent" `.compute()` calls like these, and rather raise exceptions.
Best, Peter
> [feat] Explicitly raise `TracerConversionError` when a tracer is used in a context that requires a concrete value

- .gitignore
- src/dask_awkward/lib/core.py
- tests/test_core.py
This follows the implementation of `dask.array.Array`: https://github.com/dask/dask/blob/main/dask/array/core.py#L1442
With this PR it is possible to `dask.graph_manipulation.clone` graphs containing `dask_awkward.Arrays`.
> fix: allow renaming when rebuilding dask-awkward Arrays

- pyproject.toml
- src/dask_awkward/layers/layers.py
- src/dask_awkward/lib/core.py
- src/dask_awkward/lib/optimize.py
@martindurant we got pretty... erm direct... feedback that backwards compatibility would be appreciated.
Also the current check was not working with very recent, but older, dask that has `Task` but it isn't used in blockwise.
> fix: relax dask version requirement and use a better check for Task

- src/dask_awkward/layers/layers.py
- src/dask_awkward/lib/core.py
- src/dask_awkward/lib/inspect.py
- src/dask_awkward/lib/optimize.py
- src/dask_awkward/lib/unproject_layout.py
Although we are soon to rework this, I'm updating the docs in case I run out of time in my other PR reviews.
This is a good opportunity to explain how buffer optimisation currently works.
In dask-awkward, there are two separate concepts:
- `buffer` -- a 1D array of data that Awkward Array consumes in `ak.from_buffers`
- `column` -- a possibly-structured "array-like" whose structure / type depends upon the IO source.
Each IO source has its own type of `column` in this language -- uproot has `TTree` keys, whilst Parquet has `fields`. The importance of the distinction is that remapped arrays may have a convoluted "column-buffer" relationship, e.g. arrays which share the offsets _buffer_ from a singular IO source `column`.
Given that the details of buffer projection need to be defined by the …
> docs: add better code-docs on buffer optimisation

- src/dask_awkward/layers/layers.py
- src/dask_awkward/lib/io/io.py
- tests/test_io.py
This class was removed from dask itself, and dask-awkward is presently broken with latest dask because of that.
> fix: DataFrameTreeReduction is no longer part of dask

- .github/workflows/conda-tests.yml
- .github/workflows/pypi-tests.yml
- pyproject.toml
- src/dask_awkward/lib/io/io.py
I hope I haven't forgotten any places?
> chore: drop python 3.8

- src/dask_awkward/lib/core.py
- tests/test_core.py
Fixes #553.
Now, the token is generated deterministically and thus the `dak_cache` is hit correctly for multiple repetitive invocations of `dak.map_partitions` with the same arguments.
Unfortunately I couldn't use `__dask_tokenize__` because one needs to repack the `args` and `kwargs` correctly.
Not sure how much of a performance gain there is, would be nice to measure it somehow...
> fix: tokenization of ArgsKwargsPackedFunction

- src/dask_awkward/lib/core.py
- tests/test_core.py
Justification: if the dependencies are already flat there's no need to unpack them.
> perf: go direct to _map_partitions in functions that receive already flat deps

- src/dask_awkward/lib/unproject_layout.py
Awkward does not support `index_nplike` anymore with https://github.com/scikit-hep/awkward/pull/3446 (we need to wait for a new release here). This PR replaces `index_nplike` with `nplike`.
> fix: remove `index_nplike`

- src/dask_awkward/lib/core.py
This fixes: https://github.com/dask-contrib/dask-awkward/pull/578#issuecomment-2813033447
> fix: explicit primitive promotion for scalar typetracer arrays

- src/dask_awkward/lib/core.py
- tests/test_getitem.py
This fixes slices like `array[0:0]`. Without this PR dask-awkward would wrongly slice nothing at all, ie returning the original unsliced array.
> fix: length 0 slices

- src/dask_awkward/lib/structure.py
Update the available keywords in `dak.values_astype`'s signature to match those of `ak.values_astype`
> fix: Add including_unknown kwarg to values_astype

- src/dask_awkward/pickle.py
Dask-awkward registers a global pickler which will be used if someone tries to pickle an `ak.Array` if dask-awkward just exists in the environment (not even imported). Therefore it should handle virtual buffers too by simply materializing them. Users may run into `TypeError: a bytes-like object is required, not 'VirtualNDArray'` otherwise coming from `PickleBuffer`.
This was the easiest way for me to not break backwards compatibility with earlier versions of awkward and also not doing try except statements with `ImportError` to check if awkward is new-enough to implement virtual arrays. Let me know if you think there is a nicer way.
> feat: handle virtual array in pickling
