- .github/workflows/tests.yml
- tests/environment-3.7.yml
- tests/environment-3.8.yml
- tests/environment-3.9.yml
Use `conda` environments for testing on supported Python versions.
> GitHub actions for tests

- .github/workflows/conda-tests.yml
- .github/workflows/pypi-tests.yml
- pyproject.toml
- setup.cfg
- src/dask_awkward/__init__.py
- src/dask_awkward/core.py
- src/dask_awkward/routines.py
- src/dask_awkward/utils.py
- tests/test_core.py
- tests/test_getitem.py
- Some organization.
- Working on repr (both basic and notebook).
- `__getitem__` work.
- handling cases that categorize as relatively simple (trivial `map_partitions` flavor)
- Tweaking GH actions setup.
- Add ability to calculate `divisions`
> repr, getitem, divisions, and other misc. development

- docs/examples/sandbox.py
- src/dask_awkward/core.py
- src/dask_awkward/data/__init__.py
- src/dask_awkward/utils.py
- tests/test_core.py
- tests/test_getitem.py
- tests/test_routines.py
- tests/test_utils.py
- implement single integer `__getitem__`
- required ability to eagerly compute divisions
- more organization work
> more __getitem__ work

- .coveragerc
- .github/workflows/pypi-tests.yml
- docs/api.rst
- docs/examples/20211111.ipynb
- docs/examples/demo-00.ipynb
- pyproject.toml
- src/dask_awkward/__init__.py
- src/dask_awkward/core.py
- src/dask_awkward/io.py
- src/dask_awkward/routines.py
- src/dask_awkward/tests/helpers.py
- src/dask_awkward/tests/test_core.py
- src/dask_awkward/tests/test_getitem.py
- src/dask_awkward/tests/test_ufunc.py
- src/dask_awkward/tests/test_utils.py
- src/dask_awkward/utils.py
Things targeted in this PR:
- Name collection `Array`
- Defining the top level `dask_awkward as dak` namespace.
- Start testing 3.10.
- Improve test suite design
- and getting coverage percent in the 90's.
> Naming; more test re-org; add coverage; test 3.10

- docs/index.rst
- docs/terminology.rst
After some discussion in Slack I thought it would be a good idea to put something in writing. Obviously we can expand on this as needed. I quickly jotted these thoughts down, happy to get some more input! @jpivarski @martindurant
> Terminology page

- src/dask_awkward/core.py
- src/dask_awkward/tests/helpers.py
- src/dask_awkward/tests/test_core.py
- src/dask_awkward/tests/test_getitem.py
- src/dask_awkward/tests/test_reducers.py
- src/dask_awkward/tests/test_ufunc.py
- src/dask_awkward/utils.py
Part of #23 
(also moved `assert_eq`)
> Array.__getitem__ with single integer key

- src/dask_awkward/core.py
- src/dask_awkward/tests/helpers.py
- src/dask_awkward/tests/test_core.py
- src/dask_awkward/tests/test_getitem.py
- Adding a `Record` class; behaves similar to `Scalar` but has a `__getitem__` method.
- Some test infra improvements
> Add a Record class; test improvements

- .github/workflows/conda-tests.yml
- .github/workflows/pypi-tests.yml
- src/dask_awkward/core.py
- src/dask_awkward/tests/test_getitem.py
- Support boolean array collections as input to `Array.__getitem__`
- Improve `Array.__dir__` and `Record.__dir__` for IPython things
- Test infra.
> __getitem__ for boolean arrays; other misc. things

- .coveragerc
- .github/envs/environment-3.8.yml
- .github/envs/environment-3.9.yml
- .github/workflows/coverage.yml
- .github/workflows/pypi-tests.yml
- .readthedocs.yml
- docs/api_array.rst
- docs/api_io.rst
- docs/index.rst
- docs/intro.rst
- setup.cfg
- src/dask_awkward/__init__.py
- src/dask_awkward/core.py
- src/dask_awkward/reducers.py
- src/dask_awkward/structure.py
- src/dask_awkward/tests/test_core.py
- src/dask_awkward/tests/test_getitem.py
- src/dask_awkward/tests/test_reducers.py
- src/dask_awkward/tests/test_structure.py
- src/dask_awkward/tests/test_ufunc.py
- Working on reducer/structure functions
- Use a project specific not implemented exception with a message pointing to the issue tracker
- Try to determine a new meta (typetracer) in `map_partitions`; warn if it's not possible
- Add ability to create `Scalar` collection from a known object (a narrower-focused `Delayed` like object wrapping an int or float)
- More work on Sphinx docs
> Work on reducer/structure, metadata determination, other misc.

- src/dask_awkward/core.py
- Bring in `cull` to `__dask_optimize__` methods.
- Improve function used to compute the first partition. This function is used when an array collection is created with an unknown typetracer (meta).
> cull in optimizations; better first partition compute

- src/dask_awkward/io/io.py
- tests/test_io.py
Fix a bug discovered by @kkothari2001 for single Delayed instances
> Fix single Delayed object input in from_delayed.

- src/dask_awkward/layers/layers.py
- src/dask_awkward/lib/core.py
- src/dask_awkward/lib/io/io.py
- src/dask_awkward/lib/io/scratch.py
- src/dask_awkward/lib/optimize.py
Part 2 following #76 - now we try to determine which columns to project
> Column projection

- .pre-commit-config.yaml
- src/dask_awkward/awkward.yaml
- src/dask_awkward/layers/layers.py
- src/dask_awkward/lib/core.py
- src/dask_awkward/lib/io/parquet.py
- src/dask_awkward/lib/optimize.py
- tests/conftest.py
- tests/test_distributed.py
- tests/test_layers.py
- tests/test_optimize.py
@martindurant Here is what I mentioned earlier today-- like I said,
haven't investigated the failures at all yet!
> Column projection: continue work on optimization add to dak.from_parquet

- .github/envs/environment-3.8.yml
- .github/envs/environment-3.9.yml
- .github/workflows/conda-tests.yml
- .github/workflows/coverage.yml
- .github/workflows/pypi-tests.yml
- README.md
- docs/intro.rst
- pyproject.toml
- src/dask_awkward/lib/core.py
- src/dask_awkward/lib/io/io.py
- src/dask_awkward/lib/io/json.py
- src/dask_awkward/lib/io/parquet.py
- src/dask_awkward/lib/io/scratch.py
- src/dask_awkward/lib/reducers.py
- src/dask_awkward/lib/structure.py
- src/dask_awkward/lib/testutils.py
- tests/conftest.py
- tests/test_behavior.py
- tests/test_core.py
- tests/test_describe.py
- tests/test_distributed.py
- tests/test_getitem.py
- tests/test_io.py
- tests/test_parquet.py
- tests/test_reducers.py
- tests/test_structure.py
- tests/test_ufunc.py
- rename import; awkward._v2 to awkward
- remove commented lines
> Update awkward import (remove `_v2`)

- pyproject.toml
- src/dask_awkward/lib/__init__.py
- src/dask_awkward/lib/core.py
- src/dask_awkward/lib/io/json.py
- src/dask_awkward/lib/optimize.py
- src/dask_awkward/utils.py
- tests/conftest.py
- tests/test_io.py
- tests/test_layers.py
- Add `to_json` top level function.
- Add support for using `shema=` in `from_json`
> More JSON dev

- .flake8
- .pre-commit-config.yaml
- pyproject.toml
- tests/test_utils.py
> Use ruff over flake8

- src/dask_awkward/lib/reducers.py
- tests/test_reducers.py
Adding more map-partitionalble reducers (axis >= 1 support)
> More reducers

- src/dask_awkward/lib/inspect.py
- src/dask_awkward/lib/io/parquet.py
- src/dask_awkward/lib/optimize.py
- tests/conftest.py
- tests/test_inspect.py
> Fix getitem optimization such that only starting fields can be discovered as necessary

- src/dask_awkward/lib/structure.py
Usual meta patch-over with `length_zero_array`
@agoose77 FYI
> Remove need for explicit calc in dak.with_name

- .github/workflows/conda-tests.yml
- .github/workflows/coverage.yml
- .github/workflows/pypi-tests.yml
- src/dask_awkward/lib/core.py
- src/dask_awkward/lib/reducers.py
- src/dask_awkward/lib/structure.py
- tests/test_core.py
- tests/test_structure.py
This is a followup to scikit-hep/awkward#2154
> UnknownScalar removal

- .github/workflows/conda-tests.yml
- .github/workflows/coverage.yml
- .github/workflows/pypi-tests.yml
- src/dask_awkward/lib/core.py
- tests/test_getitem.py
- tests/test_structure.py
> support argsort result as a  where argument

- src/dask_awkward/lib/core.py
- src/dask_awkward/lib/operations.py
- tests/test_operations.py
> Relax partition/division checks for dak.concatenate

- src/dask_awkward/layers/layers.py
> Protect against empty project_columns argument

- src/dask_awkward/layers/layers.py
- src/dask_awkward/lib/inspect.py
- tests/test_io.py
> reorder column projection

- src/dask_awkward/lib/structure.py
This pull request is meant to inform @agoose77 and @jpivarski that there's something to follow up in awkward-array.
With this patch the complete jetmet correction stack works without problems in dak.
> touch 'what' argument by hand in dak.with_field

- docs/dev-contributing.rst
> fix: update dev docs

- pyproject.toml
- src/dask_awkward/lib/structure.py
Will not function correctly until https://github.com/scikit-hep/awkward/pull/2375 is merged and released.
I'll add a new pin to this PR once it is out.
@jpivarski @agoose77
> Remove workaround in cartesian; increase minimum awkward version

- src/dask_awkward/lib/structure.py
- tests/test_structure.py
Necessary to complete ADL query 8, cell 10 [here](https://github.com/CoffeaTeam/coffea-benchmarks/blob/coffea2023/coffea-adl-benchmarks.ipynb)
> feat: add dak.local_index

- src/dask_awkward/lib/structure.py
> fix: remove _meta workaround in run_lengths

- src/dask_awkward/lib/structure.py
as in title, no longer necessary
> fix: remove meta workaround in dak.isclose

- src/dask_awkward/lib/optimize.py
> tidy: remove unnecessary loop over layers for mocking

- src/dask_awkward/lib/optimize.py
This was clobbering linear chains from dask.array, like `x * 0.8` as seen over in the tests of: https://github.com/dask-contrib/dask-histogram/pull/82
Have verified locally that this fixes the test failures for that otherwise unrelated PR, while also not spoiling the optimization for dak layers.
> fix: only run linear-chains optimization on AwkwardBlockwiseLayers

- src/dask_awkward/lib/structure.py
- tests/test_structure.py
> feat: dak.mask

- docs/api-inspect.rst
- docs/index.rst
- src/dask_awkward/layers/__init__.py
- src/dask_awkward/layers/layers.py
- src/dask_awkward/lib/__init__.py
- src/dask_awkward/lib/core.py
- src/dask_awkward/lib/inspect.py
- src/dask_awkward/lib/optimize.py
- tests/test_core.py
- tests/test_inspect.py
> feat: add `head`, `sample` and axis 0 slicing

- README.md
Sorry that I forgot about this earlier, but these messages are important (all papers and software products supported by the NSF should have them).
> Add acknowledgments section to README.md.

- src/dask_awkward/lib/core.py
> fix: incorrect assumption on layer ordering

- src/dask_awkward/lib/core.py
Adds support for using `ak.XXX` functions with `dask_awkward.Array` objects.
> feat: add `Array.__awkward_function__` method

- src/dask_awkward/lib/core.py
- tests/test_core.py
- add support for dask.array.Array in map_partitions
- add test
> feat: support for `dask.array` collections in `map_partitions`

- src/dask_awkward/lib/optimize.py
> fix: in optimization pass only ask scheduler for a single compute

- src/dask_awkward/lib/io/parquet.py
While working on column projection for JSON input it was quite confusing to see `schema` used as the `form` in our parquet reading code. Schema means something very different in JSON terminology, but use of the word `form` between JSON and Parquet reading w.r.t. (dask-)awkward is identical, so we should use them consistently.
> chore: rename `schema` -> `form` in internal parquet code

- docs/conf.py
- src/dask_awkward/lib/io/parquet.py
continuing story from #328, now for writing
> fix: sync `to_parquet` arguments

- src/dask_awkward/lib/structure.py
- tests/test_structure.py
> fix: properly handle mapping version of (arg)cartesian for at least dicts

- src/dask_awkward/lib/io/io.py
- tests/test_io.py
- tests/test_operations.py
This adds the necessary columns optimization interface to the class function that `from_awkward` is based on. cc @nsmith-
~(still needs a test)~
> feat: make `from_awkward` compatible with `necessary_columns`

- src/dask_awkward/lib/core.py
- src/dask_awkward/lib/structure.py
> perf: use _map_partitions in __array_ufunc__, with_field

- pyproject.toml
- src/dask_awkward/lib/core.py
@lgray , this doesn't actually work, but I thought you would appreciate a glimpse of what I had in mind.
> feat: cache map_partitions ops

- src/dask_awkward/lib/structure.py
- tests/test_structure.py
For the case that N is bigger than npartitions or does not exactly divide
> fix: n_to_one repartition

- pyproject.toml
- src/dask_awkward/lib/io/io.py
- src/dask_awkward/lib/optimize.py
- tests/test_core.py
Fixes #561 
Only for dask >= 2024.12.0 now.
> fix: deal with kwargs when using _task_spec

- pyproject.toml
- tests/test_distributed.py
Continues: https://github.com/dask-contrib/dask-awkward/pull/572
c.f. https://github.com/dask-contrib/dask-awkward/issues/573
> deps: unpin dask
